services:
    mc:
        image: itzg/minecraft-server
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        environment:
            VERSION: 1.21.1
            EULA: "TRUE"
            TYPE: "FABRIC"
            MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
            DIFFICULTY: "normal"
            PLAYER_IDLE_TIMEOUT: -1
            SIMULATION_DISTANCE: 8
            VIEW_DISTANCE: 32
            MODRINTH_PROJECTS:
                entityculling,
                ferrite-core,
                modernfix,
                chunky,
                double-doors,
                dynamic-lights,
                axes-are-weapons,
                tree-harvester,
                ore-harvester,
                villager-names-serilum,
                dismount-entity,
                tectonic,
                lithium,
                dungeons-and-taverns,
                doors-closed
        volumes:
            - ./data:/data
